CREATE TABLE INTERACTIVE_MESSAGES.dbo.LOGIN_MESSAGES(
    Id BIGINT NOT NULL IDENTITY PRIMARY KEY,
    Active BIT NOT NULL,
    AndroidVersion NVARCHAR(64),
    AndroidMessage NVARCHAR(1000),
    IosVersion NVARCHAR(64),
    IosMessage NVARCHAR(1000),
    Type INT NOT NULL,
    IosBlocked BIT NOT NULL,
    AndroidBlocked BIT NOT NULL,
    StartTime DATETIME,
    EndTime DATETIME,
    Created DATETIME NOT NULL,
    Modified DATETIME NOT NULL
);