CREATE TABLE INTERACTIVE_MESSAGES.dbo.MESSAGES(
    ID BIGINT,
    TYPE INT,
    ACTIVE BIT,
    URGENT BIT,
    ISTARGETED BIT,
    TITLE NVARCHAR(1000),
    BODY NVARCHAR(MAX),
    IMAGE NVARCHAR(MAX),
    IMAGEURL NVARCHAR(256),
    STARTDATE DATETIME,
    ENDDATE DATETIME,
    CREATED DATETIME,
    MODIFIED DATETIME  
);

CREATE TABLE INTERACTIVE_MESSAGES.dbo.TARGET_MESSAGES(
    ID BIGINT,
    ACKNOWLEDGED_DATE DATETIME,
    ACKNOWLEDGED BIT,
    UID NVARCHAR(512),
    MESSAGE_ID BIGINT,
    CREATED DATETIME,
    MODIFIED DATETIME  
);