CREATE TABLE INTERACTIVE_MESSAGES.dbo.MESSAGES(
    ID BIGINT,
    TYPE INT,
    URGENT BIT,
    ISTARGETED BIT,
    TITLE NVARCHAR(MAX),
    BODY NVARCHAR(MAX),
    IMAGE NVARCHAR(MAX),
    IMAGEURL NVARCHAR(400),
    STARTDATE DATETIME,
    ENDDATE DATETIME,
    CREATED DATETIME,
    MODIFIED DATETIME  
);

CREATE TABLE INTERACTIVE_MESSAGES.dbo.TARGET_MESSAGES(
    ID BIGINT,
    ACKNOWLEDGED_DATE DATETIME,
    ACKNOWLEDGED BIT,
    UID BIGINT,
    CREATED DATETIME,
    MODIFIED DATETIME  
);