CREATE TABLE INTERACTIVE_MESSAGES.dbo.MESSAGES(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    TYPE INT NOT NULL,
    ACTIVE BIT NOT NULL,
    URGENT BIT  NOT NULL,
    ISTARGETED BIT NOT NULL,
    TITLE NVARCHAR(1000),
    BODY NVARCHAR(MAX),
    LINK NVARCHAR(256),
    IMAGE NVARCHAR(MAX),
    IMAGEURL NVARCHAR(256),
    STARTDATE DATETIME NOT NULL,
    ENDDATE DATETIME NOT NULL,
    CREATED DATETIME NOT NULL,
    MODIFIED DATETIME NOT NULL  
);

CREATE TABLE INTERACTIVE_MESSAGES.dbo.TARGET_MESSAGES(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    ACKNOWLEDGED_DATE DATETIME,
    ACKNOWLEDGED BIT,
    UID NVARCHAR(512) NOT NULL,
    MESSAGE_ID BIGINT NOT NULL,
    CREATED DATETIME NOT NULL,
    MODIFIED DATETIME NOT NULL
);